### ISSUE TITLE
[IPYNB_vs_HTML]_wrong_tag/numbering_in_math_expressions_of_IPYNB_files

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python-programming#111]
Hi @mmcky and @AakashGfude  , good morning!

After comparing IPYNB and HTML files for all programming lectures, I noticed an important issue in the tags or numbering in math expressions of [jupyter notebooks](https://github.com/quantecon/lecture-python-programming.notebooks):
- the numbering or tags for math expressions or equations in IPYNB files is different from those in HTML files,
- when we cited those equations in both versions, the citation formats are the same.

For example, let's consider the lecture python_oop and look at the same equation, equation (1) in the [ipynb](https://github.com/QuantEcon/lecture-python-programming.notebooks/blob/master/python_oop.ipynb) (you need to view it in Anaconda or VS code)and equation (7.1) in the [HTML](https://python-programming.quantecon.org/python_oop.html#example-the-solow-growth-model):
- In the following contexts of that equation, we cited the equation 3 times but using the tag/numbering the same as that in our website/HTML file (i.e., (7.1)).

You can also see this issue clearly from the following screenshot, where I labelled the equation tags with red lines.

![Screen Shot 2020-12-06 at 11 11 46 am](https://user-images.githubusercontent.com/53931041/101268126-ea080580-37b3-11eb-8b64-86327bc94fcc.png)

Look forward to your comments.

Other issues I noticed are coming soon.

**Comment by mmcky** [comment]
thanks @shlff -- this is driven by the `sphinx-tojupyter` using `tags` in the equation environment. It is interesting the body text has the correct equation numbering but the equation itself has an incorrect tag. Nice pickup!

**Comment by mmcky** [comment]
This will be fixed in `sphinx-tojupyter==0.1.2`

**Comment by mmcky** [comment]
thanks @shlff this is now fixed by #155
