### ISSUE TITLE
[IPYNB_vs_HTML]_missing_contents_in_HTML(website)_for_each_lecture

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python-programming#112]
Morning @mmcky and @AakashGfude ,

I noticed that there are contents for each lecture in the IPYNB files, which, however, are missing in the website/HTML files. For example, for lecture about_py, please see
- [IPYNB file](https://github.com/QuantEcon/lecture-python-programming.notebooks/blob/master/about_py.ipynb), for which there are simply contents,
- [HTML file](https://python-programming.quantecon.org/about_py.html), which shows no contents for this lecture.

You can also see it from the following screenshot, where I labelled the contents with red lines:
![Screen Shot 2020-12-07 at 7 45 10 am](https://user-images.githubusercontent.com/53931041/101291933-6eb05d80-3860-11eb-9873-ed8bb5c7b83d.png)

Do you think it is a good idea to add contents, consistent with those in the IPYNB files, to the website/HTML files?

I find there are detailed contents for the new lecture series ``continuous-time Markov Chain``, e.g., please see one of their lectures, [memoryless](https://jstac.github.io/continuous_time_mcs/memoryless.html), its contents are on the top right-hand side and will not disappear as we scroll down, which looks really cool!

Please look at this:
![Screen Shot 2020-12-07 at 7 48 41 am](https://user-images.githubusercontent.com/53931041/101291987-ba630700-3860-11eb-969f-8eeb0ba7d9d0.png)

Do you think it is a good idea to make the contents specific to each lecture like what we have in lectures ``continuous-time Markov Chain``?

**Comment by mmcky** [comment]
thanks @shlff -- the theme puts that contents on the right hand margin for `html` so I think this difference is ok. 

Will you be using `quantecon-book-theme` for the `continuous Markov Chain` lectures -- if so -- then they will get the same contents as python-programming.
