### ISSUE TITLE
[IPYNB_vs_HTML]_numbering_for_titles_of_lecture-section-subsection-subsubsection

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python-programming#113]
Hi @mmcky and @AakashGfude ,

I noticed that unlike the numbering system for titles of lectures, sections, subsections, etc. in the website/HTML files, we do not have such numbering system in the downloaded jupyter notebook. For example, please see those for lecture about_py here:
![Screen Shot 2020-12-07 at 8 08 06 am](https://user-images.githubusercontent.com/53931041/101292416-6e659180-3863-11eb-9102-5dee29c5db33.png)

Do you think it is a good idea to keep the numbering system for titles in IPYNB files consistent with those in the website?

**Comment by mmcky** [comment]
thanks @shlff it is certainly a nice to have feature.

**Comment by mmcky** [comment]
Closing here and will track on sphinx-tojupyter
