### ISSUE TITLE
[IPYNB_vs_HTML]_numbering_for_lists_in_normal_lecture_contexts

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python-programming#114]
Morning @mmcky and @AakashGfude , 

I find another issue that the numbering for some lists in normal lecture contexts can be problematic:
- in source files, we just number some lists with ``1. ....``, ``1. ...``, ``1. ...``, etc.
- but when they are converted into IPYNB and HTML files, they look differently: IPYNB (still ``1. ....``, ``1. ...``, ``1. ...``, etc.) vs HTML (``1. ....``, ``2. ...``, ``3. ...``, etc.)

For example, please see the lecture getting_started here:
![Screen Shot 2020-12-07 at 8 34 00 am](https://user-images.githubusercontent.com/53931041/101292998-0add6300-3867-11eb-8c77-4d4f2bcb160b.png)

I also notice this issue in some other lectures in basic and advanced lectures. 

Do you think it is a better idea to modify the source files directly or do something in the converting job?

**Comment by mmcky** [comment]
thanks @shlff this is helpful.

**Comment by shlff** [comment]
Thanks for your comments, @mmcky . 

I just double-checked these issues, and find this one has been solved.
- The numbering for all lists in downloaded notebooks look fine in Anaconda environment.

I will close this issue.
