### ISSUE TITLE
[Set_Default_Figure_Size]_for_figures_generated_by_code

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python-programming#115]
Morning @jstac , @mmcky and @AakashGfude ,

In all our QE lectures, we have two kinds of figures: 
1. figures generated by code and
2. figures directly inserted into the contexts.

As we discussed a long time ago and elsewhere (in Feb and in some other places), we'd love to set the default size for most figures in the 1st category (possibly the 2nd category as well?).
- For some other special figures in the 1st category, we can specify their figure size directly in the plotting code.

Right now, we use the code ``plt.rcParams['figure.figsize'] = (10,6)`` explicitly in the ``imports`` part to set the default figure-plot size in a lecture.
- e.g., please see [imports in the lecture python_by_example](https://python-programming.quantecon.org/python_by_example.html#version-1)

As we discussed before, we may want to embed this setting into the conversion process.

Anyway, I think our current migration for programming lectures should be a good place for us to start this job. 

I'd love to hear your comments.

(We could create another issue for setting default figure size for the 2nd category figures as mentioned above.)

**Comment by mmcky** [comment]
@shlff there was some discussion around this on the `jupyter-book` side of things and the consensus was there shouldn't be code that changes output that isn't contained in the notebook (i.e. code injection). So I have added the minimal code to change `matplotlib` figure sizes using the `rcParams`

**Comment by shlff** [comment]
Thanks @mmcky , do you think whether we should make the default-figure-size setting in other lectures consistent with these lectures using ``rcParams``?

**Comment by mmcky** [comment]
hi @shlff -- certainly once they are migrated to `jupyter-book`. Currently `lecture-python` and `lecture-python-advanced` are built from `rst` so use `sphinxcontrib-jupyter` so images are sized in a different way.
