### ISSUE TITLE
[pandas]_an_incomplete_inserted_figure_in_exercise_1

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python-programming#119]
Hi @jstac and @mmcky , I find the x-axis label of the inserted figure in exercise 1 of lecture [pandas](https://python-programming.quantecon.org/pandas.html#exercise-1) is incomplete (please see following). 

![Screen Shot 2021-01-04 at 6 09 29 pm](https://user-images.githubusercontent.com/53931041/103509871-2fede180-4eb8-11eb-9219-d7b1606b4743.png)

and I suggest that we should update this figure.

**Comment by mmcky** [comment]
@shlff would you have time to submit a PR to close this?
