### ISSUE TITLE
Referring to URL of lectures does not work

### ISSUE THREAD

**Issue by sayaikegawa** [QuantEcon/lecture-python-programming#12]
Hi @mmcky ,

In lectures, it often refers to other lectures and codes written  in own lecture. However, this does not work in all lectures in myst.
(referring to Wikipedia or other website works ok)

For example:
in [An introductory Example](https://5f5f3879598fe1455097dc6b--epic-agnesi-957267.netlify.app/python_by_example.html#imports), it refers to [Numpy](https://5f5f3879598fe1455097dc6b--epic-agnesi-957267.netlify.app/numpy.html). So, Numpy should be written blue like below in current  website
![Screen Shot 2020-09-14 at 9 52 37 pm](https://user-images.githubusercontent.com/44494439/93082630-9ca85a80-f6d4-11ea-81ec-cff23f090eac.png)

however, in netlify.app,
![Screen Shot 2020-09-14 at 9 53 06 pm](https://user-images.githubusercontent.com/44494439/93082669-acc03a00-f6d4-11ea-8d56-46e3d9254ad8.png)

In rst file:
```
The first line imports :doc:`NumPy <numpy>`, a favorite Python package for tasks like
```
But in Myst: ``<numpy>`` is dropped.
```
The first line imports NumPy, a favorite Python package for tasks like
```

**Comment by mmcky** [comment]
thanks @sayaikegawa this is now fixed in #21
