### ISSUE TITLE
Referring to equation does not work

### ISSUE THREAD

**Issue by sayaikegawa** [QuantEcon/lecture-python-programming#13]
Hi @mmcky ,

Referring to equations by allocated number does not work.
For example:
In website, Equation (1) is referred by the sentence " A steady state of the model is a k that solves (1)  when kt+1=kt=k."
![Screen Shot 2020-09-14 at 10 31 18 pm](https://user-images.githubusercontent.com/44494439/93086143-0414d900-f6da-11ea-963b-edc0115acf65.png)

However, in netlify.app, the sentence become " A steady state of the model is a 𝑘 that solves solow_lom when 𝑘𝑡+1=𝑘𝑡=𝑘."
It does not refer to equation by (1).
![Screen Shot 2020-09-14 at 10 33 00 pm](https://user-images.githubusercontent.com/44494439/93086291-41796680-f6da-11ea-99c3-b1041fe8a244.png)

In rst, 
```
A **steady state** of the model is a :math:`k` that solves :eq:`solow_lom` when :math:`k_{t+1} = k_t = k`.
```
In myst, ``:eq:`` is dropped.
```
A **steady state** of the model is a $k$ that solves `solow_lom` when $k_{t+1} = k_t = k$.
```

**Comment by mmcky** [comment]
Nicely documented issue -- thanks @sayaikegawa

**Comment by mmcky** [comment]
This is now fixed in https://github.com/mmcky/sphinxcontrib-tomyst/pull/54. Thanks @sayaikegawa
