### ISSUE TITLE
Adding Style Sheets to Chapter 10 (Matplotlib)

### ISSUE THREAD

**Issue by HumphreyYang** [QuantEcon/lecture-python-programming#203]

**Comment by mmcky** [comment]
@HumphreyYang what is your intention with this issue? Can you add a description. Usually style sheets are related to a theme of some kind?

**Comment by HumphreyYang** [comment]
> @HumphreyYang what is your intention with this issue? Can you add a description. Usually style sheets are related to a theme of some kind? 

Hi Matt,

Thanks for your comment. John sent me a link last week on the style sheet and asked me whether we should add a section on it. I think it is a useful tool to generate visualisations with a uniform style.

So I plan to add a section on how to use default style sheets and potentially how to create your own style sheet. I planned to discuss these details in today's meeting with @jstac.

**Comment by mmcky** [comment]
Oh OK so you're thinking about `matplotlib` / `seaborn` plots etc.?

**Comment by HumphreyYang** [comment]
> Oh OK so you're thinking about `matplotlib` / `seaborn` plots etc.?

Yes. Sorry, I should have a more informative title for this issue.

**Comment by mmcky** [comment]
> > Oh OK so you're thinking about `matplotlib` / `seaborn` plots etc.?
> 
> Yes. Sorry, I should have a more informative title for this issue.

Thanks @HumphreyYang love your work.
