### ISSUE TITLE
Add discussion of broadcasting in NumPy

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-python-programming#206]
Add to NumPy lecture?

The images here are very helpful: https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html

We could make our own or link to that lecture.

Ideally, we would have

- the rules
- some images to provide intuition
- a discussion of how broadcasting can minimize loops
- an economic example

**Comment by HumphreyYang** [comment]
Thanks for sharing. These graphs look great. I will keep these suggestions in mind when I review chapter 9.

**Comment by mmcky** [comment]
@jstac I think broadcasting is one of the most confusing aspects of `numpy` arrays. I think this would be a great addition.

**Comment by mmcky** [comment]
@HumphreyYang there are also some reference notes available to review on the data science site. 

https://datascience.quantecon.org/scientific/numpy_arrays.html#broadcasting-operations

but `Jake Van der Plas` is an excellent teacher.
