### ISSUE TITLE
Add link to About Python lecture

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-python-programming#211]
@HumphreyYang , this is a nice article about the rise and rise of Python: https://pythoncircle.com/post/763/the-rising-popularity-of-python/

Perhaps it could be included in the About Python lecture, somewhere near the top?

**Comment by HumphreyYang** [comment]
add a link to the stylesheet section of matplotlib: https://www.datafantic.com/the-magic-of-matplotlib-stylesheets/
