### ISSUE TITLE
Add a lecture on JAX

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-python-programming#224]
CC @mmcky @Smit-create @HumphreyYang @thomassargent30 

Perhaps it's time for us to add a lecture on JAX?  

We can build one off this notebook: https://github.com/QuantEcon/cbc_workshops/blob/main/day_4/jax_intro.ipynb .

We can run it on the CPU for now but recommend use of Colab and discuss how to change the runtime on Colab to add a GPU.

There are a couple of other notebooks in the same directory that could be blended in.  In particular

* https://github.com/QuantEcon/cbc_workshops/blob/main/day_4/equilib_nd.ipynb
* https://github.com/QuantEcon/cbc_workshops/blob/main/day_4/european_option_jax.ipynb

**Comment by jstac** [comment]
Perhaps @Smit-create can take the first pass on this, reviewing and improving the first notebook.

**Comment by mmcky** [comment]
- [ ] @mmcky to setup a custom GitHub runner for access to `GPU` on the QuantEcon server with a good graphics card.

**Comment by Smit-create** [comment]
> Perhaps @Smit-create can take the first pass on this, reviewing and improving the first notebook.

Sure, I'll take a look at it this week.
