### ISSUE TITLE
Update all hints and notes in text with hint and note admonitions

### ISSUE THREAD

**Issue by HumphreyYang** [QuantEcon/lecture-python-programming#225]
This issue is set up to maintain the consistency of style across the lecture series.

**Comment by mmcky** [comment]
@HumphreyYang would you be able to review lecture-python and lecture-python-advanced as well?

**Comment by HumphreyYang** [comment]
> @HumphreyYang would you be able to review lecture-python and lecture-python-advanced as well?

Sure, I will create an issue in the corresponding repo.
