### ISSUE TITLE
Check Preview

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-programming#228]
@HumphreyYang once this is complete

https://github.com/QuantEcon/lecture-python-programming.myst/actions/runs/3140451120/jobs/5101847481

would you mind to have a quick look at the preview and let me know if all your edits look good. (just a 5min check would be great)

**Comment by mmcky** [comment]
Once you close this issue I will publish to the live site

**Comment by mmcky** [comment]
https://epic-agnesi-957267.netlify.app/intro.html

**Comment by mmcky** [comment]
@HumphreyYang this is looking good to me.

**Comment by HumphreyYang** [comment]
Thanks @mmcky, looks like everything is shown correctly. Closing this now.
