### ISSUE TITLE
Reorder pandas lecture / new section

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-python-programming#229]
I suggest that we push the pandas lecture https://python-programming.quantecon.org/pandas.html above the lectures on numba and parallelization.

Then we start a new part of the lecture series titled "High performance computing".

In it we put numba, parallelization, multithreading and JAX.

If @mmcky and @thomassargent30 don't object then I'd  be glad if @HumphreyYang can help with the change.

**Comment by mmcky** [comment]
@jstac I think that is a good idea

**Comment by jstac** [comment]
Thanks @HumphreyYang  and @mmcky.  @HumphreyYang , please proceed when you have time.

> In it we put numba, parallelization, multithreading and JAX.

I guess this should be something like 

1. Numba
2.  Parallelization via Multithreading
3.  JAX  (which I'll add very soon)
4. Parallelization via Multiprocessing
