### ISSUE TITLE
Add speed comparison for broadcasting exercise in NumPy lecture

### ISSUE THREAD

**Issue by natashawatkins** [QuantEcon/lecture-python-programming#230]
I saw that there was a new exercise in the NumPy lecture ([Exercise 9.4](https://python-programming.quantecon.org/numpy.html#exercises)), but I thought maybe it would be more useful for illustrating broadcasting if the reader is asked to use compare the speeds of broadcasting vs. using the for-loop they write.

**Comment by jstac** [comment]
Good point @natashawatkins .  

@HumphreyYang , how about 

- adding `np.random.seed(123)` here so the output is the same for all readers
- adding a second part to the exercise where 4 is replaced by a large number and the reader is asked to time a for loop against the broadcast implementation.
