### ISSUE TITLE
Typo in namespaces section?

### ISSUE THREAD

**Issue by natashawatkins** [QuantEcon/lecture-python-programming#231]
Is the file [here](https://python-programming.quantecon.org/oop_intro.html#namespaces) created meant to be called `mathfoo.py` not `math2.py`?

In the line:
> To see this in action, suppose we write a script `math2.py` with a single line

**Comment by jstac** [comment]
Thanks @natashawatkins , appreciated.  @HumphreyYang , can you please review and add a PR as required?
