### ISSUE TITLE
Data from yfinance is Missing in Pandas Exercise Solutions

### ISSUE THREAD

**Issue by HumphreyYang** [QuantEcon/lecture-python-programming#246]
Hi @mmcky,

I found the data from the `yfiance` API is missing in the [solutions of Pandas lecture exercise 1 and 2](https://python-programming.quantecon.org/pandas.html#pd_ex2). I tried to retrieve data locally, and the API actually returned data for the missing values. Since we did not encounter this issue before, I am not sure if the issue is caused by the new EC2 runner.

**Comment by mmcky** [comment]
thanks @HumphreyYang hmm. might just be a once off failure of the `api` I'll trigger a new build and see if that fixes the issue

**Comment by mmcky** [comment]
This is just impacting `Nikkei` right?

**Comment by HumphreyYang** [comment]
BA in exercise 1 is also missing.

**Comment by mmcky** [comment]
@HumphreyYang I am getting this missing data when I run the notebook locally

<img width="961" alt="Screenshot 2022-11-02 at 2 59 45 pm" src="https://user-images.githubusercontent.com/8263752/199392550-39868ad9-f60a-4947-98df-5da17a4502d1.png">

**Comment by HumphreyYang** [comment]
Thanks @mmcky.

That is very strange. I ran it in iPython locally, and the API returned normally. Same for BA.

<img width="428" alt="Screenshot 2022-11-02 at 15 05 06" src="https://user-images.githubusercontent.com/39026988/199393126-99938a31-dd0c-4eec-a241-79b9f88f857a.png">

**Comment by HumphreyYang** [comment]
Sorry @mmcky, 

I accidentally deleted your comment. I will look into this issue.
