### ISSUE TITLE
Add a lecture on Dask?

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-python-programming#263]
This is something we have discussed for a while, with @HumphreyYang as the lead.

From what I've heard, it's hard to come up with compelling examples and also hard to implement examples in a realistic way.

I propose that we drop this idea and ask @HumphreyYang to focus on JAX conversions instead.

CC @mmcky @AakashGfude

**Comment by HumphreyYang** [comment]
Hi everyone, 

I am closing this for now. Please feel free to reopen it.
