### ISSUE TITLE
Issue with Cache build  + requests

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-programming#286]
@HumphreyYang would you have time to look into 

https://github.com/QuantEcon/lecture-python-programming.myst/actions/runs/5862885332/job/15895452611

and see what the issue might be re: cache builds on this repo

this occurred after merging the `SymPy` lecture but may or may not be related

**Comment by mmcky** [comment]
@HumphreyYang the switch in backends to GitHub actions didn't fix the issue so I think it is likely related to the `SymPy` lecture in some way.

**Comment by HumphreyYang** [comment]
Hi @mmcky,

This seems to be related to the corrupted `requests` package:
https://stackoverflow.com/questions/54552367/pip-cannot-find-metadata-file-environmenterror

I think `sympy` lecture did not use `requests` module. 

Should we try to reinstall the `requests` package in the env?

**Comment by mmcky** [comment]
🤔 strange. I am running a local fresh build now to see if we can replicate this issue

**Comment by mmcky** [comment]
@HumphreyYang I think I have an idea.
