### ISSUE TITLE
[pandas] Image seems elongated / distorted from natural size

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-programming#30]
<img width="1176" alt="Screen Shot 2020-09-23 at 3 54 30 pm" src="https://user-images.githubusercontent.com/8263752/93972304-5aa6a500-fdb5-11ea-8629-8c1f7c0a4ade.png">

**Comment by mmcky** [comment]
It looks like the `:scale:` parameter is transferrin correctly but this looks different under the new theme. We may need to review the number used in this manually. Using `25` instead of `55` produces:

<img width="1176" alt="Screen Shot 2020-09-28 at 2 59 06 pm" src="https://user-images.githubusercontent.com/8263752/94392342-4ab70880-019b-11eb-96bd-d233a82ebd8f.png">

**Comment by mmcky** [comment]
@AakashGfude / @DrDrij will `scale` relate to the entire page or the content pane? On the old build system it looks like scaling related to the content column rather than the page as a whole.

**Comment by AakashGfude** [comment]
@mmcky . `scale` I think should be related to the original size of the image. it is reduced to 55% of its original size here I suppose. The original size of the image you are referring to is pretty big
<img width="1787" alt="Screen Shot 2020-09-28 at 5 07 53 pm" src="https://user-images.githubusercontent.com/6542997/94400984-44318c80-01ad-11eb-9c0d-b9b2b95eb8c8.png">

we will have to visit images and adjust the scale parameter according to this new design.

**Comment by mmcky** [comment]
@AakashGfude what I don't understand is the current site uses the same setting and it looks very different. 

https://python-programming.quantecon.org/pandas.html#Overview

The `html` specifies `scale` such as:

```html
<img src="_static/lecture_specific/pandas/pandas_vs_rest.png" style="width:55%;height:55%">
```

while the `jupyter-book` build does pass that through to the `html`:

```html
<img alt="_images/pandas_vs_rest.png" src="_images/pandas_vs_rest.png" style="width: 1134.65px; height: 687.5px;">
```

**Comment by AakashGfude** [comment]
@mmcky I think the difference is because of the way it is handled in the translators of these two projects . For example `sphinxcontrib-jupyter` handles it in `%` as can be seen in: https://github.com/QuantEcon/sphinxcontrib-jupyter/blob/master/sphinxcontrib/jupyter/writers/translate_all.py#L227

**Comment by mmcky** [comment]
I see. so `html` translator doesn't pass through scale parameters to `html` but resizes the underlying image. 

- [x] this image in pandas should be changed from 55 to 30

**Comment by AakashGfude** [comment]
@mmcky right. the translator handles the logic itself.

**Comment by mmcky** [comment]
fixed by https://github.com/QuantEcon/lecture-python-programming.myst/pull/74
