### ISSUE TITLE
Link that refers to particular sections of lecture doesn't work

### ISSUE THREAD

**Issue by sayaikegawa** [QuantEcon/lecture-python-programming#33]
Hi @mmcky,
The link that refers to particular sections of lecture doesn't work.

Good examples are as follows:
In [scipy lecture,](https://python-programming.quantecon.org/scipy.html#Exercise-1) 'recursive function calls' and 'described above' should refer to other particular sections in lectures like current website.

[Website]
![Screen Shot 2020-09-23 at 8 44 41 pm](https://user-images.githubusercontent.com/44494439/94002731-9ce3dc80-fddd-11ea-815c-02c0d05ed53f.png)

[netlify app]
![Screen Shot 2020-09-23 at 8 44 00 pm](https://user-images.githubusercontent.com/44494439/94002653-8473c200-fddd-11ea-8054-3bd175f7ecf1.png)

**Comment by mmcky** [comment]
fixed by: https://github.com/QuantEcon/sphinxcontrib-tomyst/pull/73
