### ISSUE TITLE
only:: is ignored 

### ISSUE THREAD

**Issue by sayaikegawa** [QuantEcon/lecture-python-programming#34]
Hi @mmcky ,
[Here](https://python-programming.quantecon.org/pandas.html#DataFrames), the sentence "Let’s look at an example that reads data from the CSV file pandas/data/test_pwt.csv that can be downloaded here." is shown twice in netlify.app.
Please see the last sentence in each screenshot below.
[Website]
![Screen Shot 2020-09-23 at 9 00 02 pm](https://user-images.githubusercontent.com/44494439/94004257-c4d43f80-fddf-11ea-8ece-267e4336e61d.png)
[Netlify.app]
![Screen Shot 2020-09-23 at 9 01 21 pm](https://user-images.githubusercontent.com/44494439/94004373-f0efc080-fddf-11ea-8e51-8057a36a2ccd.png)

This issue occurs because `only::` is ignored in netlify.app as follows.
in rst,
```
.. only:: html

    Let's look at an example that reads data from the CSV file ``pandas/data/test_pwt.csv`` that can be downloaded
    :download:`here <_static/lecture_specific/pandas/data/test_pwt.csv>`.

.. only:: latex

    Let's look at an example that reads data from the CSV file ``pandas/data/test_pwt.csv`` and can be downloaded
    `here <https://lectures.quantecon.org/_downloads/pandas/data/test_pwt.csv>`__.
```

In md,
```
Let's look at an example that reads data from the CSV file `pandas/data/test_pwt.csv` that can be downloaded
<a href=_static/lecture_specific/pandas/data/test_pwt.csv download>here</a>.

Let's look at an example that reads data from the CSV file `pandas/data/test_pwt.csv` and can be downloaded
[here](https://lectures.quantecon.org/_downloads/pandas/data/test_pwt.csv).
```

**Comment by mmcky** [comment]
thanks for this nice report @sayaikegawa -- I have addressed this in https://github.com/QuantEcon/sphinxcontrib-tomyst/pull/71
