### ISSUE TITLE
[Pandas]Footnotes link does not work

### ISSUE THREAD

**Issue by sayaikegawa** [QuantEcon/lecture-python-programming#35]
Hi @mmcky ,

The link in footnotes does not work in the end of Pandas lecture.
[Website]
![Screen Shot 2020-09-23 at 9 12 37 pm](https://user-images.githubusercontent.com/44494439/94005347-83449400-fde1-11ea-85b2-7a4f7db6fb3a.png)
[netlify.app]
![Screen Shot 2020-09-23 at 9 12 57 pm](https://user-images.githubusercontent.com/44494439/94005395-9192b000-fde1-11ea-9795-368e47376134.png)

In rst,
```
.. [#mung] Wikipedia defines munging as cleaning data from one raw form into a structured, purged one.
```
In md, [link](https://python-programming.quantecon.org/pandas.html#mung-link) disappeared
```
Wikipedia defines munging as cleaning data from one raw form into a structured, purged one.
```

**Comment by mmcky** [comment]
This should be fixed by https://github.com/QuantEcon/sphinxcontrib-tomyst/pull/72
