### ISSUE TITLE
list number error (when contains math)

### ISSUE THREAD

**Issue by sayaikegawa** [QuantEcon/lecture-python-programming#36]
Hi @mmcky ,

When list contains `math`, list number goes wrong like below.
[lecture:[writing good code](https://5f61a885d6bec440579d6660--epic-agnesi-957267.netlify.app/writing_good_code.html#an-example-of-poor-code)]
![Screen Shot 2020-09-23 at 9 30 00 pm](https://user-images.githubusercontent.com/44494439/94006933-f222ec80-fde3-11ea-980f-7764967acfc7.png)

[lecture: [OOP](https://5f61a885d6bec440579d6660--epic-agnesi-957267.netlify.app/python_oop.html#exercise-2)]
![Screen Shot 2020-09-23 at 9 30 48 pm](https://user-images.githubusercontent.com/44494439/94006984-0f57bb00-fde4-11ea-865f-c9e1431bfd6b.png)

However, md does not seem to be wrong.
```
1. sets $k_0 = 1$
1. iterates using {eq}`gc_solmod` to produce a sequence $k_0, k_1, k_2 \ldots , k_T$
1. plots the sequence
```

```
1. Evaluate the polynomial {eq}`polynom`, returning $p(x)$ for any $x$.
1. Differentiate the polynomial, replacing the original coefficients with those of its derivative $p'$.
```

**Comment by mmcky** [comment]
this appears to be fixed in the latest build

[writing good code](https://5f6be72c36f4ac1d8bf34091--reverent-montalcini-de7189.netlify.app/writing_good_code.html#an-example-of-poor-code)

and

[oop](https://5f6be72c36f4ac1d8bf34091--reverent-montalcini-de7189.netlify.app/python_oop.html#exercise-2)
