### ISSUE TITLE
this particular code block does not work well

### ISSUE THREAD

**Issue by sayaikegawa** [QuantEcon/lecture-python-programming#37]
Hi @mmcky ,
In this [lecture](https://epic-agnesi-957267.netlify.app/getting_started.html#exercise-2), this code block does not work well as follows.

![Screen Shot 2020-09-24 at 1 54 29 pm](https://user-images.githubusercontent.com/44494439/94099114-7a010900-fe6d-11ea-8c5b-7f1edbe7cca7.png)
The code block shows additional > after `git clone https://github.com/QuantEcon/QuantEcon.py`.

**Comment by mmcky** [comment]
thanks @sayaikegawa this will be fixed by: https://github.com/QuantEcon/lecture-python-programming/pull/72
