### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by sayaikegawa** [QuantEcon/lecture-python-programming#39]
Hi @mmcky ,
Import errors occur when it imports `quantecon as qe`
For example, please see below in [lecture](https://epic-agnesi-957267.netlify.app/numba.html).

![Screen Shot 2020-09-24 at 2 24 18 pm](https://user-images.githubusercontent.com/44494439/94100720-a454c580-fe71-11ea-9339-b7593acc1e53.png)

**Comment by mmcky** [comment]
@sayaikegawa perhaps we should add `:class: hide-output` to these blocks?

In `myst` that will become a toggled dropdown but is hidden by default

**Comment by mmcky** [comment]
Could you list all the lectures where this is an issue below and I will fix in the `rst`.

**Comment by sayaikegawa** [comment]
Hi @mmcky,
The issue occurs only in 
[need for speed](https://epic-agnesi-957267.netlify.app/need_for_speed.html#operations-on-arrays)
[numba](https://epic-agnesi-957267.netlify.app/numba.html#numba)

I think `:class:: hide-output` may cause this issue as you said, because in myst after doing `!conda install -y quantecon`, it says environment is inconsistent and numba is not installed as the error says "Numbawarning".
![Screen Shot 2020-09-24 at 4 52 41 pm](https://user-images.githubusercontent.com/44494439/94110679-5f875980-fe86-11ea-90e3-05fa1250a7f8.png)

You can see the result of installing `!conda install -y quantecon` [here](https://epic-agnesi-957267.netlify.app/need_for_speed.html#overview) if you click "click to show" below.
![Screen Shot 2020-09-24 at 4 55 49 pm](https://user-images.githubusercontent.com/44494439/94111009-ce64b280-fe86-11ea-982b-0853bf388921.png)

**Comment by mmcky** [comment]
thanks @sayaikegawa I am inclined to leave this warning in place. It is a valid warning (within the context we run these lectures). I will try and update to `python=3.8` and the latest `anaconda=2020.07` to see if that fixes this.

**Comment by mmcky** [comment]
warnings aren't there in https://5f6d9a5257410c35b3d5dd64--epic-agnesi-957267.netlify.app/numba.html which is PR #41
