### ISSUE TITLE
Fixes Needed for sphinxcontrib-tomyst

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-programming#4]
- [x] copy of `_static` folder is not present in `_build/myst`. It will also need to be put in the `source` location rather than the `_build` location. 
- [x] `contents` directive not being parsed correctly (See #3) [fixed by [this PR](https://github.com/mmcky/sphinxcontrib-tomyst/pull/42)]

**Comment by mmcky** [comment]
@AakashGfude can you work on a fix for the missing `_static` folder given your familiar with the `builder` elements. It needs to mirror the source location. 

@mmcky to work on fixing contents directive

**Comment by AakashGfude** [comment]
sure @mmcky . On it

**Comment by AakashGfude** [comment]
@mmcky at present, the copy of static files to `_build/myst/source` is implemented by `tomyst_static_file_path` which has default value of `['_static']`. For our `lecture-python-programming` and probably also for other repos, the value required is `["source/_static"]`, which when inputting to `conf.py` results in the copying of the `_static` files.

**Comment by mmcky** [comment]
thanks @AakashGfude can you document that in `docs` via PR. You may need to start a new page for conf options etc.

**Comment by AakashGfude** [comment]
Done in https://github.com/mmcky/sphinxcontrib-tomyst/pull/44

**Comment by mmcky** [comment]
Closing this as all contained issues are resolved. Will open individual issues.
