### ISSUE TITLE
numba jitclass warning

### ISSUE THREAD

**Issue by sayaikegawa** [QuantEcon/lecture-python-programming#40]
Hi @mmcky ,
In this [lecture](https://epic-agnesi-957267.netlify.app/numba.html#compiling-classes), 
numba jitclass warning occurs. I think this issue happened in main web site lecture before...so I'm not sure this occurs because of this converting process. 

![Screen Shot 2020-09-24 at 2 30 08 pm](https://user-images.githubusercontent.com/44494439/94101057-7459f200-fe72-11ea-8805-18f3d9f05800.png)

**Comment by mmcky** [comment]
thanks @sayaikegawa we will need to update that in the source to fix that warning message.

**Comment by mmcky** [comment]
@sayaikegawa I think upgrading to `python=3.8 and anaconda=2020.07` may have fixed this warning

https://5f6d9a5257410c35b3d5dd64--epic-agnesi-957267.netlify.app/numba.html

**Comment by sayaikegawa** [comment]
Thanks @mmcky , I understand.  
(This is the on hold issue at [#145](https://github.com/QuantEcon/lecture-python/pull/145))
