### ISSUE TITLE
[theme] Home button not working

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-programming#47]
The home button doesn't take you back to the `index` page:

https://5f727dfc5850e4220dd680a0--epic-agnesi-957267.netlify.app/index_learning_python.html#

**Comment by AakashGfude** [comment]
@mmcky home button should be working at the moment. https://5f766efb6978501643da1ad5--epic-agnesi-957267.netlify.app/intro.html

**Comment by mmcky** [comment]
This is working for local but isn't for `gh-pages` (see #71)
