### ISSUE TITLE
[theme] Can `Contents` title take you back to the index page

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-programming#49]
Currently there is no obvious way to get back to the main entry page (index)

<img width="1176" alt="Screen Shot 2020-09-28 at 3 07 10 pm" src="https://user-images.githubusercontent.com/8263752/94498832-83f48480-023e-11eb-868e-e765a3a6f71b.png">

Once you leave the index page (#47) but also the top level TOC isn't available on the Left Hand Menu?

@AakashGfude is this something that might be different when we build with `jupyter-book`?

**Comment by AakashGfude** [comment]
Top level toc is visible in the latest `test-jupyter-book` branch.

**Comment by mmcky** [comment]
This isn't applicable to the latest theme iteration. Closing
