### ISSUE TITLE
[theme] how to reference download notebooks?

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-programming#50]
To support migration we will reference the old `notebooks` in `lecture-python-programming.notebooks` for now. 

How do we set this in the `theme`?

**Comment by AakashGfude** [comment]
@mmcky  for the download notebook option. we are using the notebook created by `jupyter-cache` inside the `jupyter_execute` folder.

**Comment by mmcky** [comment]
hmm -- not sure that is a good idea. What do the `image` links look like? Is there a hook we can apply to perhaps update the images with a web location?

**Comment by mmcky** [comment]
PR #100 will resolve this and support `download notebooks` locally without needing to reference external repo. We could build notebooks (as a seperate github actions and deploy to another repo) as an alternative publish pathway?
