### ISSUE TITLE
[theme] where should pdf assets go?

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-programming#51]
To support migration we will reference the old single page `pdf` from lecture-python-programming for now.

What location are pdf files pulled from?

**Comment by AakashGfude** [comment]
@mmcky have used the print function of the browser now. for download pdf option like in `sphinx-book-theme`. but we can pull it from the `build` folder as well once `--singlepagepdf` option is given.

**Comment by mmcky** [comment]
@AakashGfude we are looking to use the current set of `pdf` files for the short term on `quantecon` websites (so they won't get updates until we implement --singlepagepdf in `jupyter-book`) So I am wanting to know if we can switch that button in `quantecon-book-theme` to download the pdf from a `_downloads` folder?

**Comment by AakashGfude** [comment]
@mmcky ooh yes we can do that.

**Comment by mmcky** [comment]
@AakashGfude will close this for now and use the `pdf print` functionality.
