### ISSUE TITLE
[theme] Github Source Link?

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-programming#52]
Github Source link isn't working -- how do we specify the repo?

**Comment by AakashGfude** [comment]
@mmcky should be working now

**Comment by mmcky** [comment]
@AakashGfude the link now downloads the source file. It should direct the user to the `github` repo to make edits etc.

**Comment by mmcky** [comment]
Is this an easy fix?

**Comment by AakashGfude** [comment]
ooh ok @mmcky, so we need the user to specify the github link of his repo then?

**Comment by mmcky** [comment]
yeah it will need to in `_config.yml`

**Comment by mmcky** [comment]
this is now available.
