### ISSUE TITLE
[deploy] Route our lecture-programming.quantecon.org to gh-pages

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-programming#60]
When we deploy we will need to configure `gh-pages` to use a custom domain name. 

https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site

(cc: @DrDrij)

**Comment by AakashGfude** [comment]
@mmcky if we have a custom domain name, then probably the home page link issue in gh-pages will be resolved automatically?

**Comment by mmcky** [comment]
@AakashGfude -- not sure I follow -- won't this just redirect to `gh-pages` address?

**Comment by AakashGfude** [comment]
I mean the homepage at present is set to `/` which directs to the domain name of the page. 
with custom gh-page, will the base domain name be `lecture-python-programming` and not `https://quantecon.github.io/` in the URL?

**Comment by mmcky** [comment]
@DrDrij 

https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site

**Comment by mmcky** [comment]
This is done.
